name: Python application
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          cache: 'poetry'
      - run: make install
      - run: make lint
      - run: make test-cov
      - uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: lucasrcezimbra/dj-storage-url
