name: Upload Python Package
on:
  release:
    types: [published]
jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/dj-storage-url
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'poetry'
      - run: make install
      - run: make build
      - uses: pypa/gh-action-pypi-publish@release/v1
